import Head from 'next/head'
import {useRouter} from "next/router";
import usePhotos from "@/utils/usePhotos";
import Link from "next/link";
import usePhoto from "@/utils/usePhoto";
import Modal from "@/components/Modal";


export default function Home() {


  const router = useRouter();
  const { photoId } = router.query
  const [photo] = usePhoto(photoId)

  const [photos, isLoading] = usePhotos()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <h1 className="text-center text-4xl font-bold m-10">SakuraGram</h1>
        {photo && <Modal photo={photo}/>}
        {isLoading
          ? <p>Loading...</p>
          : <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 auto-rows-max	 gap-6 m-10">
            {photos.map(({ id, url }) => (
              <Link
                key={id}
                // href={`/photos/${id}`}
                href={{pathname: '/', query:{photoId:id}}}
                as={`/photos/${encodeURI(id)}`}
                shallow
              >
                <img
                  alt=""
                  src={url}
                  height={500}
                  width={500}
                  className="w-full object-cover aspect-square"
                />
              </Link>
            ))}
            </div>
        }

      </main>
    </>
  )
}